export const POSTS = "POSTS";
export const INCREMENT_LIKES_ALLPOST = "INCREMENT_LIKES_ALLPOST";
export const INCREMENT_LIKES_POST = "INCREMENT_LIKES_POST";
export const ADD_COMMENTS = "ADD_COMMENTS";

export const ALL_POST = "ALL_POST";

export const USER_DATA = "USER_DATA";

export const FORGOT_USER = "FORGOT_USER";

export const AUTHENTICATING = "AUTHENTICATING";

export const EDITPOST = "EDITPOST";
