export const POSTS = "POSTS";
export const INCREMENT_LIKES_ALLPOST = "INCREMENT_LIKES_ALLPOST";
export const INCREMENT_LIKES_POST = "INCREMENT_LIKES_POST";

//Comments
export const ADD_COMMENT = "ADD_COMMENT";
export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const DELETE_ALL_COMMENTS = "DELETE_ALL_COMMENTS";

export const ALL_POST = "ALL_POST";

export const USER_DATA = "USER_DATA";

export const FORGOT_USER = "FORGOT_USER";

export const AUTHENTICATING = "AUTHENTICATING";

export const EDITPOST = "EDITPOST";
